# Generated by Django 3.2.5 on 2021-08-26 16:26

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210826_2057'),
        ('learning', '0004_alter_contact_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='country',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='count', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
    ]
