# Generated by Django 3.2.5 on 2021-08-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20210826_2057'),
        ('learning', '0005_auto_20210826_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='count',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city'),
        ),
    ]
