# Generated by Django 3.2.5 on 2021-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
