# Generated by Django 3.2.5 on 2021-11-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_enterprisecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('about', models.CharField(max_length=5000)),
                ('why', models.CharField(max_length=5000)),
                ('outline', models.CharField(max_length=5000)),
                ('why_forteforge', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=256)),
                ('subcategory', models.CharField(max_length=256)),
            ],
        ),
    ]
