# Generated by Django 3.2.5 on 2021-11-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
