# Generated by Django 3.2.5 on 2021-11-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='why',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='why_forteforge',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
